name: telemetry
description: Implementation of OpenTelemetry specification
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  convert: ^3.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
