include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  plugins:
    - dart_code_metrics



dart_code_metrics:
  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  metrics:
    cyclomatic-complexity: 10
    halstead-volume: 150
    lines-of-code: 100
    maintainability-index: 50
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 9
    source-lines-of-code: 50
    weight-of-class: 0.33
  rules:
    # Common rules
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-magic-number
#    - no-object-declaration
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-first
    - prefer-last
    - prefer-trailing-comma
    - prefer-correct-identifier-length:
        max-identifier-length: 40
        min-identifier-length: 3
    - prefer-correct-type-name:
        min-length: 3
        max-length: 40
    - member-ordering-extended:
        alphabetize: false
        order:
          - public-fields
          - private-fields
          - constructors
          - getters
          - setters
          - methods
    # Flutter specific rules
    - avoid-unnecessary-setstate
    - always-remove-listener
    - prefer-const-border-radius
#    - prefer-single-widget-per-file:
#        ignore-private-widgets: true
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed