name: flate
description: Flutter state management library inspired by Verge state manager for Swift
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  synchronized: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  dart_code_metrics: 4.10.1


flutter:

