name: flate
description: This package provides a set of components for creating a flexible and scalable architecture for applications written in Flutter.
version: 0.2.0
repository: https://github.com/bysensa/flac/tree/master/packages/flate

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  synchronized: ^3.0.0+2
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  dart_code_metrics: 4.10.1
  mocktail: ^0.3.0


flutter:

