name: opentelemetry
description: Implementation of OpenTelemetry API and SDK
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:


dev_dependencies:
  test: ^1.21.1
